In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

#  Import and read the insurance.csv.
import pandas as pd 
insurance_df = pd.read_csv('Resources/insurance.csv')
insurance_df.head()

index  age     sex     bmi  children smoker     region      charges
0      0   19  female  27.900         0    yes  southwest  16884.92400
1      1   18    male  33.770         1     no  southeast   1725.55230
2      2   28    male  33.000         3     no  southeast   4449.46200
3      3   33    male  22.705         0     no  northwest  21984.47061
4      4   32    male  28.880         0     no  northwest   3866.85520

In [2]:
# Cleaning DataFrame - drop extra index column
insurance_df = insurance_df.drop(columns = ['index'])
insurance_df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
# Cleaning DataFrame - cleaning charges column
insurance_df['charges'] = insurance_df['charges'].map("{:,.2f}".format)
insurance_df

age     sex     bmi  children smoker     region    charges
0      19  female  27.900         0    yes  southwest  16,884.92
1      18    male  33.770         1     no  southeast   1,725.55
2      28    male  33.000         3     no  southeast   4,449.46
3      33    male  22.705         0     no  northwest  21,984.47
4      32    male  28.880         0     no  northwest   3,866.86
...   ...     ...     ...       ...    ...        ...        ...
1333   50    male  30.970         3     no  northwest  10,600.55
1334   18  female  31.920         0     no  northeast   2,205.98
1335   18  female  36.850         0     no  southeast   1,629.83
1336   21  female  25.800         0     no  southwest   2,007.94
1337   61  female  29.070         0    yes  northwest  29,141.36

[1338 rows x 7 columns]

In [4]:
insurance_df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges      object
dtype: object

In [7]:
# Define features set
X = insurance_df.copy()
X.drop("charges", axis=1, inplace=True)
X.head()

age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [8]:
# Define target vector
y = insurance_df["charges"].values.reshape(-1, 1)
y[:5]

array([['16,884.92'],
       ['1,725.55'],
       ['4,449.46'],
       ['21,984.47'],
       ['3,866.86']], dtype=object)

In [9]:
# Encode the categorical variables using get_dummies
X = pd.get_dummies(X)

In [10]:
X[:]

age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes  \
0      19  27.900         0           1         0          0           1   
1      18  33.770         1           0         1          1           0   
2      28  33.000         3           0         1          1           0   
3      33  22.705         0           0         1          1           0   
4      32  28.880         0           0         1          1           0   
...   ...     ...       ...         ...       ...        ...         ...   
1333   50  30.970         3           0         1          1           0   
1334   18  31.920         0           1         0          1           0   
1335   18  36.850         0           1         0          1           0   
1336   21  25.800         0           1         0          1           0   
1337   61  29.070         0           1         0          0           1   

      region_northeast  region_northwest  region_southeast  region_southwest  
0                    0                 0                 0                 1  
1                    0                 0                 1                 0  
2                    0                 0                 1                 0  
3                    0                 1                 0                 0  
4                    0                 1                 0                 0  
...                ...               ...               ...               ...  
1333                 0                 1                 0                 0  
1334                 1                 0                 0                 0  
1335                 0                 0                 1                 0  
1336                 0                 0                 0                 1  
1337                 0                 1                 0                 0  

[1338 rows x 11 columns]

In [11]:
# Split into testing and training sets using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [13]:
from sklearn.linear_model import LogisticRegression
# Declare a logistic regression model.
# Apply a random_state of 9 to the model
logistic_regression_model = LogisticRegression(random_state=9)

# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train, y_train)

/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

In [15]:
# Import the model for sklearn confusion matrix
from sklearn.metrics import confusion_matrix

# Create and save the confusion matrix for the training data
training_matrix = confusion_matrix(y_train, training_predictions)

# Print the confusion matrix for the training data
print(training_matrix)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
# Create and save the confusion matrix for the testing data
test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(test_matrix)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
# Create and save the training classification report
training_report = classification_report(y_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

    1,121.87       1.00      1.00      1.00         1
    1,131.51       0.00      0.00      0.00         1
    1,135.94       0.00      0.00      0.00         1
    1,136.40       0.00      0.00      0.00         1
    1,137.01       0.00      0.00      0.00         1
    1,137.47       0.00      0.00      0.00         1
    1,141.45       0.00      0.00      0.00         1
    1,146.80       0.50      1.00      0.67         1
    1,163.46       1.00      1.00      1.00         1
    1,241.57       0.00      0.00      0.00         1
    1,242.82       0.50      1.00      0.67         1
    1,252.41       0.00      0.00      0.00         1
    1,253.94       0.00      0.00      0.00         1
    1,256.30       0.00      0.00      0.00         1
    1,261.44       0.00      0.00      0.00         1
    1,261.86       0.00      0.00      0.00         1
    1,515.34       0.00      0.00      0.00         1
    1,534.30       0.00    

/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [18]:
# Create and save the testing classification report
testing_report = classification_report(y_test, testing_predictions)

# Print the testing classification report
print(testing_report)

              precision    recall  f1-score   support

    1,149.40       0.00      0.00      0.00       1.0
    1,163.46       0.00      0.00      0.00       0.0
    1,242.26       0.00      0.00      0.00       1.0
    1,242.82       0.00      0.00      0.00       0.0
    1,263.25       0.00      0.00      0.00       1.0
    1,391.53       0.00      0.00      0.00       1.0
    1,526.31       0.00      0.00      0.00       1.0
    1,532.47       0.00      0.00      0.00       1.0
    1,615.77       0.00      0.00      0.00       1.0
    1,621.34       0.00      0.00      0.00       1.0
    1,627.28       0.00      0.00      0.00       1.0
    1,629.83       0.00      0.00      0.00       1.0
    1,631.67       0.00      0.00      0.00       0.0
    1,633.04       0.00      0.00      0.00       1.0
    1,634.57       0.00      0.00      0.00       0.0
    1,639.56       0.00      0.00      0.00       1.0
    1,646.43       0.00      0.00      0.00       1.0
    1,665.00       0.00    

/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/j.mai.le/anaconda3/l

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)
X_train.shape

(1003, 11)

In [1]:
#Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)
classifier

LogisticRegression(random_state=1)

In [13]:
# Train the data
classifier.fit(X_train, y_train)

/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/j.mai.le/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=1)

In [14]:
# Score the model
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.46360917248255235
Testing Data Score: 0.0


In [16]:
# Predict outcomes for test data set
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

ValueError: Per-column arrays must each be 1-dimensional